services:
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - matching-service
      - cv-parsing-service
      - requirements-parsing-service
      - data-access-service

  cv-parsing-service:
    build: ./cv-parsing-service

  requirements-parsing-service:
    build: ./requirements-parsing-service
  matching-service:
    build: ./matching-service
  
  data-access-service:
    build: ./data-access-service
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/creds/key.json
    volumes:
      - ${GCP_CREDS_PATH}:/creds/key.json:ro