services:
  fastapi:
    build: .
    command: PYTHONPATH=./src python -m fastapi dev application/api_call.py
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build: .
    command: PYTHONPATH=./src python -m streamlit run application/matching_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app